document.writeln("<!-- footer -->");
document.writeln("<footer>");
document.writeln("");
document.writeln("<div id=\'copyright\'>");
document.writeln("<div class=\'container\'>");
document.writeln("<div class=\'row\'>");
document.writeln("<div class=\'col-md-12 col-sm-12\'>");
document.writeln("<hr class='hr1'>");
document.writeln("<p class=\'copyright-text\'>");
document.writeln("智雲科技股份有限公司 版權所有 <br>");
document.writeln("Copyright © Fast Distributed Cloud Computing Co.,Ltd. All rights reserved.");
document.writeln("</p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("</footer>");
document.writeln("<!-- footer -->");