document.writeln("<!-- Header  -->");
document.writeln("");
document.writeln("<nav class=\'navbar navbar-expand-md fixed-top scrolling-navbar nav-bg\'>");
document.writeln("<div class=\'container\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<div class=\'navbar-header\'>");
document.writeln("<a class=\'navbar-brand\' href=\'index.html\'>");
document.writeln("<img src=\'img/logonew.png\' alt=\'\'>");  
document.writeln("</a>");
document.writeln("<button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#main-menu\' aria-controls=\'main-menu\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("<span class=\'navbar-toggler-icon\'></span>");
document.writeln("</button>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("<div class=\'collapse navbar-collapse\' id=\'main-menu\'>");
document.writeln("");
document.writeln("<ul class=\'navbar-nav mr-auto w-100 justify-content-end\'>");
document.writeln("<li class=\'nav-item dropdown\'>");
document.writeln("<a class=\'nav-link dropdown-toggle\' id=\'main\' href=\'index.html\' aria-haspopup=\'true\' aria-expanded=\'false\'>首頁</a>");
document.writeln("</li>");
document.writeln("<li class=\'nav-item dropdown\'>");
document.writeln("<a class=\'nav-link dropdown-toggle\' id=\'about\' href=\'about.html\' aria-haspopup=\'true\' aria-expanded=\'false\'>公司簡介</a>");
document.writeln("</li>");
document.writeln("<li class=\'nav-item dropdown\'>");
document.writeln("<a class=\'nav-link dropdown-toggle\' id=\'art\' aria-haspopup=\'true\' aria-expanded=\'false\'>產品資訊</a>");
document.writeln("<div class=\'dropdown-menu\'>");
document.writeln("<a class=\'dropdown-item\' href=\'product-1.html\'>IDC機房租賃服務</a>");
document.writeln("<a class=\'dropdown-item\' href=\'product-2.html\'>客戶自選設備租賃</a>");
document.writeln("<a class=\'dropdown-item\' href=\'product-3.html\'>伺服器設備租賃</a>");
document.writeln("<a class=\'dropdown-item\' href=\'product-4.html\'>雲端服務</a>");
document.writeln("<a class=\'dropdown-item\' href=\'product-5.html\'>CDN高速內容傳遞網路服務</a>");
document.writeln("<a class=\'dropdown-item\' href=\'product-6.html\'>DDOS服務</a>");
document.writeln("</div>");
document.writeln("</li>");
document.writeln("<li class=\'nav-item dropdown\'>");
document.writeln("<a class=\'nav-link dropdown-toggle\' id=\'music\' href=\'contact.html\'  aria-haspopup=\'true\' aria-expanded=\'false\'>聯絡我們</a>");
document.writeln("</li>");
document.writeln("<li class=\'nav-item dropdown\'>");
document.writeln("<a class=\'nav-link dropdown-toggle\' href=\'https://www.facebook.com/myServer-%E6%99%BA%E9%9B%B2%E7%B2%89%E7%B5%B2%E5%9C%98-191313391750425\' target=\'_blank\' aria-haspopup=\'true\' aria-expanded=\'false\'>fb粉絲團</a>");
document.writeln("</li>");
document.writeln("");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<!--END PC-->");
document.writeln("");
document.writeln("<!-- MOB -->");
document.writeln("<ul class=\'wpb-mobile-menu\'>");
document.writeln("<li>");
document.writeln("<a class=\'active\' href=\'index.html\'>首頁</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'about.html\'>公司簡介</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'art.html\'>產品資訊</a>");
document.writeln("<ul>");
document.writeln("<li><a href=\'product-1.html\'>IDC機房租賃服務</a></li>");
document.writeln("<li><a href=\'product-2.html\'>客戶自選設備租賃</a></li>");
document.writeln("<li><a href=\'product-3.html\'>伺服器設備租賃</a></li>");
document.writeln("<li><a href=\'product-4.html\'>雲端服務</a></li>");
document.writeln("<li><a href=\'product-5.html\'>CDN高速內容傳遞網路服務</a></li>");
document.writeln("<li><a href=\'product-6.html\'>DDOS服務</a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'contact.html\'>聯絡我們</a>");
document.writeln("</li>");
document.writeln("<li>");
document.writeln("<a href=\'https://www.facebook.com/myServer-%E6%99%BA%E9%9B%B2%E7%B2%89%E7%B5%B2%E5%9C%98-191313391750425\' target=\'_blank\' ></a>f</a>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("<!-- END MOB -->");
document.writeln("");
document.writeln("</div>");
document.writeln("</nav>");
document.writeln("");
document.writeln("<!-- END  Header  -->");


function tran(){
 window.alert("敬請期待")}

